### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Thrasi**
Functioning code for finding and publishing the closest point and the approximate orientation

### CODE REVIEW

**Comment by GustavSandstroem** [comment]
the file is named "image_display.py". Otherwise functionally works fine! #cv.show is uncommeted and can be recommented to used.

**Comment by Jinxit** [comment]
The "cv" import is unnecessary and may even cause problems

#gustavscomputer #nondeterministicturingmachine

**Comment by Jinxit** [comment]
Ok

**Comment by GustavSandstroem** [comment]
ok

**Comment by Thrasi** [comment]
I added a gaussian filter to smooth a bit

**Comment by goncacp** [comment]
OK

**Pull request merged**
